version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:  
      - "5433:5432"

volumes:
    postgres: